let path = '../src/client/app/services/__tests__/'

const blockSelector = require(`${path}blockSelector.test`)
const checkArgs = require(`${path}checkArgs.test`)
const cleanArr = require(`${path}cleanArr.test`)
const compose = require(`${path}compose.test`)
const getBEM = require(`${path}getBEM.test`)
const getKeys = require(`${path}getKeys.test`)
const getLastArray = require(`${path}getLastArray.test`)
const isArraywithEls = require(`${path}isArrayWithEls.test`)
const isEmptyObject = require(`${path}isEmptyObject.test`)
const isObj = require(`${path}isObj.test`)
const isTruthy = require(`${path}isTruthy.test`)
const selectOptions = require(`${path}selectOptions.test`)
const showIfTrue = require(`${path}showIfTrue.test`)
const subSelector = require(`${path}subSelector.test`)
const enforceNumericInput = require(`${path}enforceNumericInput.test`)

// const filterPiTable = require(`${path}filterPiTable.test`)
// const filterTable = require(`${path}filterTable.test`)
