module.exports = {
    REQUEST_VALIDATE_CLIENT: "REQUEST VALIDATE CLIENT",
    RESPONSE_VALIDATE_CLIENT: "RESPONSE VALIDATE CLIENT",
    ERROR: "REST ERROR",
    REQUEST_LOCAL: "REQUEST LOCAL TABLE",
    REQUEST_BACKUP: "REQUEST BACKUP",
    REQUEST_GLOBAL: "REQUEST GLOBAL TABLE",
    REQUEST_CONLFLICTS: "REQUEST CONFLICTS",
    REQUEST_VALIDATION: "REQUEST VALIDATION",
    RESPONSE_BACKUPS: "RESPONSE BACKUPS",
    RESPONSE_RESTAPI: "RESPONSE RESTAPI",
    RESPONSE_VALIDATION: "RESPONSE VALIDATION",
}

