module.exports = {
    ERROR: "REST ERROR",
    REQUEST_LIST: "REQUEST_LIST",
    REQUEST_BACKUP: "REQUEST_BACKUP",
    REQUEST_LOCAL: "REQUEST_LOCAL_TABLE",
    REQUEST_GLOBAL: "REQUEST_GLOBAL_TABLE",
    REQUEST_CONLFLICTS: "REQUEST_CONFLICTS",
    REQUEST_VALIDATE_CLIENT: "REQUEST_VALIDATE_CLIENT",
    RESPONSE_VALIDATE_CLIENT: "RESPONSE_VALIDATE_CLIENT",
    RESPONSE_BACKUP: "RESPONSE_BACKUPS",
    RESPONSE_RESTAPI: "RESPONSE_RESTAPI",
}
