const REQUEST_VALIDATE_CLIENT = "REQUEST VALIDATE CLIENT"
const RESPONSE_VALIDATE_CLIENT = "RESPONSE VALIDATE CLIENT"

module.exports = {
    REQUEST_VALIDATE_CLIENT,
    RESPONSE_VALIDATE_CLIENT,    
}